/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-27 07:27:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>추천 Bar</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navigator -->\r\n");
      out.write("	<!-- upper navbar here -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./common/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Content -->\r\n");
      out.write("	<section class=\"py-5 text-center container\" style=\"border-bottom: 1px solid #dbdbdb;\">\r\n");
      out.write("		<div class=\"row py-lg-5\">\r\n");
      out.write("			<div class=\"col-lg-6 col-md-8 mx-auto\">\r\n");
      out.write("				<h1 class=\"fw-light\">Bar</h1>\r\n");
      out.write("				<p class=\"lead text-muted\">컨셉별 다양한 Bar를 소개합니다</p>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"album py-5 bg-light\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3\">\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"col\" style=\"height: 380px\">\r\n");
      out.write("					<a href=\"bar2\">\r\n");
      out.write("					<div class=\"card mx-auto\" style=\"width:100%; height:380px;\">				\r\n");
      out.write("					<img src=\"resources/image/slideimg.png\" width=\"100%\" height=\"100%\" >					\r\n");
      out.write("					<div class=\"card-img-overlay\">\r\n");
      out.write("					<h2 style=\"position: absolute; top: 50%; left: 50%; \r\n");
      out.write("						transform: translate(-50%, -50%); color:black;\">재즈 Bar</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col\" style=\"height: 380px\">\r\n");
      out.write("					<a href=\"bar2\">\r\n");
      out.write("					<div class=\"card mx-auto\" style=\"width:100%; height:380px;\">				\r\n");
      out.write("					<img src=\"resources/image/slideimg.png\" width=\"100%\" height=\"100%\" >					\r\n");
      out.write("					<div class=\"card-img-overlay\">\r\n");
      out.write("					<h2 style=\"position: absolute; top: 50%; left: 50%; \r\n");
      out.write("						transform: translate(-50%, -50%); color:black;\">재즈 Bar</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col\" style=\"height: 380px\">\r\n");
      out.write("					<a href=\"bar2\">\r\n");
      out.write("					<div class=\"card mx-auto\" style=\"width:100%; height:380px;\">				\r\n");
      out.write("					<img src=\"resources/image/slideimg.png\" width=\"100%\" height=\"100%\" >					\r\n");
      out.write("					<div class=\"card-img-overlay\">\r\n");
      out.write("					<h2 style=\"position: absolute; top: 50%; left: 50%; \r\n");
      out.write("						transform: translate(-50%, -50%); color:black;\">재즈 Bar</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col\" style=\"height: 380px\">\r\n");
      out.write("					<a href=\"bar2\">\r\n");
      out.write("					<div class=\"card mx-auto\" style=\"width:100%; height:380px;\">				\r\n");
      out.write("					<img src=\"resources/image/slideimg.png\" width=\"100%\" height=\"100%\" >					\r\n");
      out.write("					<div class=\"card-img-overlay\">\r\n");
      out.write("					<h2 style=\"position: absolute; top: 50%; left: 50%; \r\n");
      out.write("						transform: translate(-50%, -50%); color:black;\">재즈 Bar</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<!-- footer here -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
